app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, EqualTo, Length
from ..models import User, Agenda, Point

class AddAgendaForm(FlaskForm):
	name = StringField('Name', validators=[DataRequired(), Length(max=128)])
	create = SubmitField('Create')

class AddPointForm(FlaskForm):
	name = StringField('Name', validators=[Length(max=128)])
	content = StringField('Content', validators=[Length(max=512)])
	add = SubmitField('Add')
	
class MailingListForm(FlaskForm):
	email = StringField("Email")

app/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__)

from . import views

app/home/views.py
from flask import flash, redirect, render_template, url_for, request, abort, Response
from flask_login import login_required, current_user
import uuid
import json
from collections import defaultdict
import datetime


from forms import AddAgendaForm, AddPointForm, MailingListForm
from .. import db
from ..models import User, Agenda, Point
from . import home


# There might be a better way to set this up in the models so you can just say agenda.current_active and not worry about it
def get_current_point(agenda):
	# agenda = Agenda.query.filter_by(uuid=agenda_uuid).first()
	current_point = agenda.points[0]
	for point in agenda.points:
		if point.current_active == True:
			current_point = point
	return current_point

def get_agenda_duration(agenda):
	times = []
	s = "00:00:00"
	total_time = datetime.datetime.strptime(s, "%H:%M:%S")
	for point in agenda.points:
		try:
			point_time = datetime.timedelta(hours=int(point.hours), minutes=int(point.minutes), seconds=int(point.seconds))
			times.append(point_time)
		except Exception, e:
			pass #fail silently
	for time in times:
		total_time += time
	return total_time.strftime("%H:%M:%S")

@home.route('/signup/', methods=['POST'])
def signup():
	print(request.form.Email)
	return redirect(url_for('home.homepage'))

@home.route('/')
def homepage():
	return render_template('home/index.html', title="Welcome")

# There are two routes here because when you redirect from a 'back' press breadcrumb you want the viewed app to still be open
@home.route('/dashboard', defaults={'agenda_uuid': None})
@home.route('/dashboard/<string:agenda_uuid>')
@login_required
def dashboard(agenda_uuid):
	cur = []
	total_times = []
	agendas = current_user.agendas
	
	for agenda in agendas:

		# this handles agendas with no points
		try:
			cur.append(get_current_point(agenda))
		except Exception, e:
			cur.append("N/A")
			print str(e)

		
		total_times.append(get_agenda_duration(agenda))


	return render_template('home/dashboard.html', agendas=agendas, cur=cur,times=total_times, clicked=agenda_uuid, title="Dashboard")

# This was the old way to add agendas, I don't think it'll get used anymore
@home.route('/add/agenda/', methods=['GET', 'POST'])
@login_required
def add_agenda():
	form = AddAgendaForm()
	if form.validate_on_submit():
		#uuid might eventually run into collision problems, but that would require our service to have more users than there are currently people on the earth. So that would be something..
		agenda = Agenda(created_by = current_user.id, uuid = uuid.uuid4(), name = form.name.data)

		db.session.add(agenda)
		db.session.commit()
		flash("Your agenda has been created")
		return redirect(url_for('home.dashboard'))

	return render_template('home/agenda_create.html', form=form, title="Add Agenda")


@home.route('/add/dynamic/agenda/', methods=['POST'])
@login_required
def add_dynamic_agenda():
	if request.method == 'POST':
		info = dict(request.form)
		agenda_name = str(info['name'][0])

		agenda = Agenda(created_by = current_user.id, uuid=uuid.uuid4(), name=agenda_name)
		db.session.add(agenda)
		db.session.commit()

		info.pop('name', None)
		points = []
		counter = 0
		for key,value in info.iteritems():
			#pull names based on key data, grab the associated content and create an object
			if key.startswith('point'):
				index = key.split("_")[1]

				content_key = "content_point_{}".format(index)
				hours_key = "hours_{}".format(index)
				minutes_key = "minutes_{}".format(index)
				seconds_key = "seconds_{}".format(index)

				content_value = str(info[content_key][0])
				hours_value = int(info[hours_key][0])
				minutes_value = int(info[minutes_key][0])
				seconds_value = int(info[seconds_key][0])

				if(hours_value == 0 and minutes_value == 0 and seconds_value == 0):
					seconds_value = 1

				if hours_value > 24:
					hours_value = 24
				elif hours_value < 0:
					hours_value = 0


				if minutes_value > 59:
					minutes_value = 59
				elif minutes_value < 0:
					minutes_value = 0

				if seconds_value > 59:
					seconds_value = 59
				elif seconds_value < 0:
					seconds_value = 0

				point_name = str(value[0])
				if index == '0':
					active = True
				else:
					active = False

				# Doesn't add points with no name - definitely should make that required in the form itself.
				if point_name != "":
					point = Point(agenda=agenda.id, name=point_name, internal_order=counter, content=content_value, hours=int(hours_value), minutes=int(minutes_value), seconds=int(seconds_value), current_active=active)
					db.session.add(point)
					db.session.commit()
					counter += 1
		

	return redirect(url_for('home.dashboard', clicked=agenda.uuid))

@home.route('/delete/agenda/<string:agenda_uuid>/')
@login_required
def delete_agenda(agenda_uuid):
	agenda = Agenda.query.filter_by(uuid=agenda_uuid).first()
	if current_user.id != agenda.created_by:
		abort(404)

	db.session.delete(agenda)
	db.session.commit()
	flash("Deleted {}".format(agenda.name))

	return redirect(url_for('home.dashboard'))

# This is confusing, but I promise it's good. There are two ids. One is the database primary key. and the other is the uuid that is used
# as an external reference. So when you see agenda_id that refers usually to the uuid.
@home.route('/agenda/<string:agenda_uuid>/')
@login_required
def view_agenda(agenda_uuid):
	agenda = Agenda.query.filter_by(uuid=agenda_uuid).first()
	created_by = User.query.filter_by(id=agenda.created_by).first().username
	if agenda is None:
		abort(404)
	points = agenda.points
	li = []

	# Gather all the data from the form and points, clean it server side and spit it out as JSON - this will be used for the apps and for
	# the single page dashboard. It is fast, lightweight, and O(n) for a page load which should never be a problem.

	try:
		points = []
		for i in agenda.points:
			if i.internal_order is None:
				raise ValueError("oops")
			points.append([i, i.internal_order])
		points = sorted(points, key=lambda x:x[1])
		points = list(zip(*points)[0])
	except Exception as e:
		print(e)
		points = []
		for i in agenda.points:
			points.append([i, i.id])
		points = sorted(points, key=lambda x:x[1])
		points = list(zip(*points)[0])

	
	for i,point in enumerate(points):
		point_dict = defaultdict(str)
		point_dict['name'] = str(point.name)
		point_dict['content'] = str(point.content)
		point_dict['current_active'] = str(point.current_active)
		point_dict['duration'] = "{}:{}:{}".format(point.hours, point.minutes, point.seconds)
		li.append(dict(point_dict))
	duration = get_agenda_duration(agenda)
	agenda = agenda.__dict__
	agenda.pop('_sa_instance_state', None)

	agenda['points'] = li
	agenda['created_by'] = created_by
	agenda['duration'] = duration
	for key, value in agenda.iteritems():
		if key == 'date_created':
			agenda[key] = str(value)
	
	# return render_template('home/agenda_view.html', agenda=agenda, points=agenda.points, title=agenda.name)
	return Response(json.dumps(agenda),  mimetype='application/json')


# This will be depreciated and replaced with a monster "edit agenda" method or something - just to make it easier for people to use
@home.route('/add/point/<string:agenda_uuid>/', methods=['GET','POST'])
@login_required
def add_point(agenda_uuid):
	form = AddPointForm()
	agenda = Agenda.query.filter_by(uuid=agenda_uuid).first()
	if current_user.id != agenda.created_by:
		abort(404)
	if form.validate_on_submit():
		if current_user.id == agenda.created_by:
			point = Point(agenda = agenda.id, name=form.name.data, content = form.content.data)
			db.session.add(point)
			db.session.commit()
			flash("Your point has been added")
			return redirect(url_for('home.dashboard', clicked=agenda_uuid))

	return render_template('home/point_add.html', form=form, agenda_uuid=agenda_uuid, title="Add Point")


# currently no UX functionality for this
@home.route('/delete/point/<int:point_id>/', methods=['GET', 'POST'])
@login_required
def delete_point(point_id):
	point = Point.query.filter_by(id=point_id).first()
	if point is None:
		abort(404)
	agenda = Agenda.query.filter_by(id = point.agenda).first()
	if current_user.id != agenda.created_by:
		abort(404)

	db.session.delete(point)
	db.session.commit()
	flash("Your point as been deleted")

	return redirect(url_for('home.view_agenda', agenda_uuid=agenda.uuid))

app/templates/home/agenda_create.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Make Agenda{% endblock %}
{% block extrastyles %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}
{% block body %}
<div class="content-section">
	<br />
		{{ utils.flashed_messages() }}
	<br />
  <div class="center">
    <h1>Create an Agenda</h1>
    <br/>
    <form action="/add/dynamic/agenda/" method="POST">
    	{{form.csrf}}
    	<p><label for="name">Name</label><input type="text" name="name" class="form-control" /></p>
        

        <div class="pull-right">
        	<h4 class="col-sm-8">Add Point</h4>
        	<i class="fa fa-plus-circle add-point-button col-sm-4" style="font-size: 3em;" aria-hidden="true"></i>
        </div>

        <button type="submit" class="btn btn-default">Submit</button>

	</form>

  </div>

</div>
{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
// This code handles the dynamic form, it's not pretty, and will need to be updated for UX purposes, but it works great right now.
$(document).ready(function(){
	var count = 0;

    // var spinner = $( ".hours" ).spinner();
    

	$(".add-point-button").unbind('click').bind('click', function(){
        var time_picker = "<p class='col-sm-4'><label for='hours_{0}'>Hours</label><input type='number' value='0' name='hours_{0}' class='hours form-control' min='0' max='24' /></p>\n<p class='col-sm-4'><label for='minutes_{0}'>Minutes</label><input type='number'  value='0'  name='minutes_{0}' class='minutes form-control' min='0' max='59' /></p>\n<p class='col-sm-4'><label for='seconds_{0}'>Seconds</label><input type='number' value='1' name='seconds_{0}' class='seconds form-control' min='0' max='59' /></p>".format(count);
		var point_name = "<div class='point-content'><p><label for='point_{0}'>Point</label><input type='text' name='point_{0}' class='form-control' /></p>".format(count);
		var point_content = "<p><label for='content_point_{0}'>Content</label><textarea name='content_point_{0}' class='form-control' rows='3' /></p></div>".format(count);
		$(time_picker + point_name + point_content).insertBefore(".pull-right");
		count += 1;


        


        $(".hours").unbind('change').bind('change', function(){
            if($(this).val() < 0 || $(this).val() > 24){
                $(this).parent().wrap("<div class='has-error'></div>");
            }else{
                if($(this).parent().parent().hasClass('has-error')){
                    $(this).parent().unwrap("<div class='has-error'></div>");
                }  
            }
        })

        $(".minutes").unbind('change').bind('change', function(){
            if($(this).val() < 0 || $(this).val() > 59){
                $(this).parent().wrap("<div class='has-error'></div>");                
            }else{
                if($(this).parent().parent().hasClass('has-error')){
                    $(this).parent().unwrap("<div class='has-error'></div>");                    
                }
            }
        })

        $(".seconds").unbind('change').bind('change', function(){
            if($(this).val() < 0 || $(this).val() > 59){
                $(this).parent().wrap("<div class='has-error'></div>");
            }else{
                if($(this).parent().parent().hasClass('has-error')){
                    $(this).parent().unwrap("<div class='has-error'></div>");                    
                }
            }
        })


	});
})
</script>
{% endblock %}

app/templates/home/agenda_view.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
            	<!-- Messages -->
            	{% with messages = get_flashed_messages() %}
				  {% if messages %}
				    {% for message in messages %}
					 <div class="alert alert-warning alert-dismissible" role="alert">
					 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
						{{message}}
					 </div>
					{% endfor %}
				  {% endif %}
				{% endwith %}

				<!-- Agenda List -->
                <div class="col-md-12">
                    <h1>{{agenda.name}}</h1>
                    <hr class="intro-divider">
                    {% if points|length == 0 %}
                    	<h3>No points</h3>
                    {% else %}

	                    <div class="points"><!-- add class sortable-items for reordering -->
	                    {% for point in points %}
                        <div class="point {%if point.current_active == True%}active pulsate{% endif %}">
                            <a href="/delete/point/{{point.id}}" class="delete">x</a>
	                    	<span>{{point.name}}</span><br />
                            <span>{{point.content}}</span>
                        </div>
	                    {% endfor %}
	                	</div>
	                {% endif %}                    
                    </div>
                </div>
                <div class="col-lg-12 button-group">
                	<a href="/add/point/{{agenda.uuid}}" class="btn btn-default">Add point</a>
                    <a href="/view/{{agenda.uuid}}" class="btn btn-default">Present</a>
                </div>	
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrascripts %}
<script type="text/javascript">
$(document).ready(function(){
    $(".delete").click(function(){
        return confirm("Are you sure you want to delete this point?");
    });
})
</script>

{% endblock %}

app/templates/home/dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
            	<!-- Messages -->
            	{% with messages = get_flashed_messages() %}
				  {% if messages %}
				    {% for message in messages %}
					 <div class="alert alert-warning alert-dismissible" role="alert">
					 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
						{{message}}
					 </div>
					{% endfor %}
				  {% endif %}
				{% endwith %}

				<!-- Agenda List -->
                <div class="col-sm-6">
                    <h3>My Agendas</h3>
                    <hr class="intro-divider">
                    {% if agendas|length == 0 %}
                    	<h3>You don't have any agendas</h3>
                    {% else %}
                    <table class="table">
                    	<thead>
                    		<th></th>
                    		<th>Name</th>
                    		<th>Date</th>
                            <th>Meeting Length</th>
                    		<th>Share</th>
                    	</thead>
                    	<tbody>
                    		{% for agenda in agendas %}
                    			<tr>
                    				<td><a href="/delete/agenda/{{agenda.uuid}}" class="delete">x</a></td>
                    				<td><span class="agenda-name" uuid="{{agenda.uuid}}">{{agenda.name}}</span></td>
                    				<td>{{agenda}}</td>
                                    <!-- <td><a href="{{url_for('present.present_agenda', agenda_uuid=agenda.uuid)}}">{{cur[loop.index0]}}</a></td> -->
                                    <td><a href="{{url_for('present.present_agenda', agenda_uuid=agenda.uuid)}}">{{times[loop.index0]}}</a></td>
                                    <td><a href="#" data-toggle="popover" title="URL" data-content="/view/{{agenda.uuid}}"><i class="fa fa-share share" uuid="{{agenda.uuid}}"></i></a></td>
                    			</tr>
                    		{% endfor %}
                    	</tbody>
                    </table>
	                {% endif %}                    
                
	                <div class="button-group">
	                	<a href="{{url_for('home.add_agenda')}}" class="btn btn-normal btn-block">Add Agenda</a>
	                </div>	
                </div>

                <!-- The sidebar is initially hidden, maybe we can have some placeholder something instead  -->
                <div class="col-sm-5 side-bar pull-right" style="display:none;">
                    <h3 class="side-bar-name"></h3>
                    <hr class="intro-divider">
                    <ul class="side-bar-list">
                    </ul>

                    <span class="side-bar-button"></span>
                    

                </div>




            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrascripts %}
<script src="{{url_for('static', filename='js/dashboard.js')}}">
</script>

{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block body %}

<div>  <!-- class="container" -->
    <div class="index-header"> <!--  class="intro-header" -->
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message" > <!-- class="intro-message" -->
                    <h1 class="fade-in">Megenda</h1>
                    <h3 class="fade-in">Make the most out of your meetings</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="index-header"> <!--  class="intro-header" -->
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message" > <!-- class="intro-message" -->
                    <!-- <h1 class="fade-in">Our Mission</h1> -->
                    <h4 class="fade-in">We want your meetings to be effective. We are working hard to build an ecosystem that allows you to easily create, share, and use agendas in your meetings.</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="index-header"> <!--  class="intro-header" -->
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message" > <!-- class="intro-message" -->
                    <h1 class="fade-in">Learn More</h1>
                    <h3 class="fade-in">Sign up for our mailing list and get updates about Megenda's progress</h3>
                        <div class="col-md-10 fade-in" style="margin-top:15px;">
                            <form method="POST" action="/signup/">
                                <div class="input-group form-search">
                                    <input type="email" name="Email" class="form-control search-query" placeholder="Enter your email to stay up to date"/>
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-primary" data-type="last">Sign Up</button>
                                    </span>
                                </div>
                            </form>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

app/templates/home/point_add.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Add Point{% endblock %}
{% block body %}

<div class="content-section">
	<a href="/agenda/{{agenda_uuid}}">back</a>
	<!-- Messages -->
	{% with messages = get_flashed_messages() %}
	  {% if messages %}
	    {% for message in messages %}
		 <div class="alert alert-warning alert-dismissible" role="alert">
		 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
			{{message}}
		 </div>
		{% endfor %}
	  {% endif %}
	{% endwith %}
  <div class="center">
    <h1>Add a Point</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}